### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by farnaf** [Tantime/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
  - please include a screenshot of the fix -- print statements don't fix a bug
- [x] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1
  - what specifically was the bug? and its relationship with the symptom

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
  - we're looking for a code change in MarkdownParse.java, the change that fixes the bug you describe in this part
- [x] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
we're looking for **3 code changes** you made in MarkdownParse.java that fix 3 bugs or attempt to fix a bug with 3 different inputs. all the code changes you have in your report address one single bug and show none of the fixes.

nice work so far 😃 
Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by Tantime** [comment]
So does this mean I'm allowed to focus on one bug as long as I show three different inputs and fixes affected by said bug?

**Comment by farnaf** [comment]
Yep, the bugs can be the same as long as the test files and the code changes are different
